# ------------------------------------------------------------------------------------------
# This is a workflow to build an bootable Armbian SD card image with a Linux kernel
# and appropriate boot images to setup the NAND on a Cubietruck (SUNXI A20 board)
# for:
#   - SUNXI NAND support within mainline kernel
#   - booting from NAND with mainline U-Boot
#   - have a NAND partition configured for an UBI filesystem
#
# ------------------------------------------------------------------------------------------
name: Build Armbian for Cubietruck (dryrun)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dryrun'
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+-dryrun'
  #push:
  #  branches:
  #    - master
  #    - boards/cubietruck
  #schedule:
  #    - cron: 0 8 * * 5

jobs:
  job1_Build:
    name: Build Armbian Image for Cubietruck
    uses: MHARMBIAN/build_actions/.github/workflows/__build_armbian.yml@master
    with:
      runner: ubuntu-latest
      uploading: true
      dryrun: true
      ARMBIAN_RELEASE_TAG: v2023.03.29-wip
      BUILD_MINIMAL: yes
      KERNEL_GIT: shallow
      KERNEL_CONFIGURE: no
      BOARD: cubietruck
      BRANCH: legacy
      RELEASE: jammy
      BUILD_DESKTOP: no
      IMAGE_COMPRESS_ENDING: xz
      # REPOSITORY_INSTALL (comma-separated list): list of core packages which will be installed from repository
      # Available options: u-boot, kernel, bsp, armbian-bsp-cli,armbian-bsp-desktop,armbian-desktop,armbian-config, armbian-firmware
      # list, what is not wanted to be built
      # U-Boot only:
      # REPOSITORY_INSTALL: "kernel,armbian-bsp-cli,armbian-bsp-desktop,armbian-desktop,armbian-config,armbian-firmware"
      REPOSITORY_INSTALL: ""

  job2_logUploadedArtifactNames:
    name: Log uploaded artifact names
    runs-on: ubuntu-latest
    needs: job1_Build
    steps:
      # Log use case if triggered manually
      - name: Log use case if triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Workflow has been triggered manually"

      # Log use case if triggered by push
      - name: Log use case if triggered by push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Workflow has been triggered by push to ${{ github.ref }}"

      - name: Log Uploaded Artifacts
        run: |
          echo "  image_UploadArtifactName:    ${{ needs.job1_Build.outputs.image_UploadArtifactName }}"
          echo "  packages_UploadArtifactName: ${{ needs.job1_Build.outputs.packages_UploadArtifactName }}"
          echo "  logfiles_UploadArtifactName: ${{ needs.job1_Build.outputs.logfiles_UploadArtifactName }}"

  job3_Release:
    name: Release Uploaded Artifacts
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: job1_Build
    uses: MHARMBIAN/build_actions/.github/workflows/__release_build_artifacts.yml@master
    with:
      runner: ubuntu-latest
      image_UploadArtifactName:    ${{ needs.job1_Build.outputs.image_UploadArtifactName }}
      packages_UploadArtifactName: ${{ needs.job1_Build.outputs.packages_UploadArtifactName }}
      logfiles_UploadArtifactName: ${{ needs.job1_Build.outputs.logfiles_UploadArtifactName }}
      board_Name:                  ${{ needs.job1_Build.outputs.board_Name }}
      image_CompressEnding:        ${{ needs.job1_Build.outputs.image_CompressEnding }}
